import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MirageSetup from "@/components/MirageSetup";

export const metadata: Metadata = {
  title: "Snapp! Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MirageSetup>{children}</MirageSetup>
      </body>
    </html>
  );
}
